baseURL: 'http://garden.fammatre.org/'
languageCode: 'en-us'
title: 'Fammatre Elementary School Garden'
paginate: 5
theme: 'PaperMod'

# Generate a robots.txt file
enableRobotsTXT: true

# PaperMod search config (search.md and fuse.js)
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# Papermod theme options
params:
  # Set theme to light
  defaultTheme: light

  # Don't show the theme toggle
  disableThemeToggle: true

  # Show social media share buttons on posts
  ShowShareButtons: true

  # Show suggestions for other posts at the end of posts
  ShowPostNavLinks: true

  # Hide the default footer
  hideFooter: true

menu:
  main:
    - identifier: news
      name: News
      url: /news/
      weight: 10
    - identifier: planting-schedule
      name: Planting Schedule
      url: /planting-schedule/
      weight: 20
    - identifier: grant-resources
      name: Grant Resources
      url: /garden-grant-resources
      weight: 30
    - identifier: about
      name: Who we are
      url: /about/
      weight: 40
